name: Automacao Medical Insight 24h
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora cheia
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  executar_curadoria:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o CÃ³digo
        uses: actions/checkout@v4

      - name: Instalando Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodando o Worker
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ENTREZ_EMAIL: ${{ secrets.ENTREZ_EMAIL }}
        run: python worker.py